package br.com.redesurftank.havalshisuku.models;

public enum ServiceManagerEventType {
    CLUSTER_CARD_CHANGED,
    CLUSTER_INPUT_KEY,
    STEERING_WHEEL_AC_CONTROL,
    GRAPH_SCREEN_NAVIGATION,
    UPDATE_SCREEN,
    MENU_ITEM_NAVIGATION,
    MAX_AUTO_AC_STATUS_CHANGED,
    DISPLAY_SCREEN_SELECTION,
    DISPLAY_1_APP_STATE_CHANGED,
    DISPLAY_3_APP_STATE_CHANGED,
    APP_GEOMETRY_CHANGED,
    DISMISS_WARNING,
    RAW_KEY_EVENT
}
